project:
  type: website
  output-dir: docs

website:
  title: "Andrew Lim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        href: about.html
      - text: "Data Viz"
        menu: 
         - text: "Chess"
           href: chess.html
         - text: "Carbon Emissions"
           href: emissions.html

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    page-layout: full

editor: visual

