---
title: "Ethics"
---

**Ethics Discussion**

In 2015, researchers published an dataset scraped from 60,000 OkCupid dating profiles. The following discussion explores the questions of ethics surrounding this incident.

The dataset was intended for use in introductory data science classes, from which students could use to practice anonymization or discuss data science ethics (Xiao 2021). While the researchers may have had productive intentions, the publication of the dataset was of questionable ethicality. Although the researchers tried to anonymize the data, they collected many important identifiers that could be used to identify users. Additionally, the collection of data was against OkCupid’s terms of service, and users were unaware that their data could be used and published in such a way.

A similar incident occured in 2016 when Dutch researchers published a dataset scraped from 70,000 OkCupid profiles (Resnick 2016). The Dutch researchers made no attempt to anonymize the data, given all the information was already “public” since it was available online. However, others argue that publishing the information was unethical since the information is not entirely public in that it is intended only for other OkCupid users and the gathering of data was done without OkCupid’s permission. Another ethical questions arising from this situation is regarding academia. The Dutch researchers were able to publish this data through the Open Science Framework, a platform intended to increase transparency and decrease gatekeeping in academia. However, the potential for harm like in this case raises questions regarding whether we should decrease barriers in academia, or if they serve a valid, useful purpose.

Below I evaluate the processes used and identify the shortcomings of the OkCupid cases.

### What is the permission / consent structure for using the data? Was if followed?

Consent is a freely given, informed, specific, and revocable agreement from a data subject that their information may be collected, analyzed, or shared for clearly stated purposes. Consent is important because it respects the autonomy and dignity of people and their information. No direct permission was received from OkCupid or from its users. The profiles were scraped from the website without any authorization. In addition, users could not have anticipated that their data would be published for use in an academic setting. This was a violation of the users’ autonomy and dignity in that it publicly exposed their personal information without their permission.

### Is the data identifiable and sufficiently anonymized?

Identifiability is the ability to identify the source of data given the data points. Sufficiently anonymized data makes it so that people can not identify the exact entity from which the data came from. In cases where the data is regarding people, identifiability makes it so one can identify an individual based on their recorded characteristics, while anonymized data works to prevent this. In the OkCupid cases, the data was identifiable and not sufficiently anonymized, meaning that that one could identify certain individuals based on their reported characteristics, such as age, location, among other factors. The identifiability of the data violated users’ privacy since anyone interested could extract personal information about certain individuals from the dataset.

### What was the data-collection process, and was it ethical?

An ethical data-collection process should have protections for participants, ensure security of data, and result in anonymized data. The OkCupid data was collected via web‑scraping without platform approval, and arguably violated the Computer Fraud and Abuse Act. It was not ethical since it was done without permission from any of the involved parties. The argument used by the Dutch researchers (that the information was already public) does not hold since the information was only partially public (only available for a target demographic to see). An ethical data-collection process would have required the permission of all users involved and the platform to ensure that only people who are okay with their information being published are included.

### Were the data made publicly available, and are they being used in unintended ways?

Ideally, sensitive data is shared only through a secure, access‑controlled repository under a license that restricts use to the specific, consented‑to purposes. The OkCupid data was made publicly available on the open web. Users’ personal essays, interests, and other identifying traits were freely downloadable. The release online meant that the data could be used for anything and everything beyond its intended classroom use. This constituted an ethical breach because it violates users’ peronal agency over their information (even if they consented to the study). The published information could be used for things like identifying people based on political beliefs or sexuality. A possible solution could be a gated-access model, in which access to the data could be regulated and controlled (Xiao 2021).

Interestingly enough, despite the backlash regarding the data's publication, it is still available online, taking only 2 minute Google search to find.

[Citations]{.underline}

-   OK Cupid data release (privacy and publicly available data). Xiao, T., and Ma, Y. (2021), [A Letter to the Journal of Statistics and Data Science Education — A Call for Review of ‘OkCupid Data for Introductory Statistics and Data Science Courses’ by Albert Y. Kim and Adriana Escobedo-Land](https://www.tandfonline.com/doi/full/10.1080/26939169.2021.1930812), Journal of Statistics and Data Science Education, 29, 214–215.

-   Resnick, Brian. “Researchers Just Released Profile Data on 70,000 Okcupid Users without Permission.” Vox, Vox, 12 May 2016, [www.vox.com/2016/5/12/11666116/70000-okcupid-users-data-release](http://www.vox.com/2016/5/12/11666116/70000-okcupid-users-data-release).
